version: "3.0"
services:
   namenode:
      image: apache/hadoop:3
      hostname: namenode
      container_name: namenode
      command: ["hdfs", "namenode"]
      ports:
        - 9870:9870
        - 9000:9000
      env_file:
        - ./config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
      networks:
        - dsa_net
   datanode:
      image: apache/hadoop:3
      container_name: datanode
      hostname: datanode
      command: ["hdfs", "datanode"]
      ports:
        - 9864:9864
      env_file:
        - ./config
      networks:
        - dsa_net
   resourcemanager:
      image: apache/hadoop:3
      hostname: resourcemanager
      command: ["yarn", "resourcemanager"]
      ports:
         - 8088:8088
      env_file:
        - ./config
      volumes:
        - ./test.sh:/opt/test.sh
      networks:
        - dsa_net
   nodemanager:
      image: apache/hadoop:3
      command: ["yarn", "nodemanager"]
      env_file:
        - ./config
      networks:
        - dsa_net

networks:
  dsa_net:
    driver: bridge